version: "3.9"
secrets:
  kraig_social_github_webhook_secret:
    external: true
services:
  web:
    image: ghcr.io/kraigwalker/kraig-social:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GITHUB_WEBHOOK_SECRET_FILE=/run/secrets/kraig_social_github_webhook_secret
    secrets:
      - kraig_social_github_webhook_secret
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
