version: "3.9"
secrets:
  kraig_social_github_webhook_secret:
    external: true
services:
  secrets:
    kraig_social_github_webhook_secret:
      external: true
  web:
    image: ghcr.io/kraigwalker/kraig-social:latest
    secrets:
      - kraig_social_github_webhook_secret
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
